### ISSUE TITLE
proto.002-PsYLVpVv.contract.unrevealed_key

### ISSUE THREAD

**Issue by munakaya** [LMilfont/TezosJ-plainjava#1]
Hi, thank you for the good library.
I excute below code.
balance check is working but send operation failed.
Can I get some tip why it failed due to "contract.unrevealed_key" ?

tz1hjWhmmaLbtzrqhkAoeFiTp5U9mt7kcjtu is known account in my private node.

`TezosWallet myLoadedWallet = new TezosWallet(true, "c:\\temp\\mySavedWallet.txt", "myPassphrase");
System.out.println("Loaded the wallet from disk:");
System.out.println(myLoadedWallet.getPublicKeyHash());
System.out.println(myLoadedWallet.getBalance());  
BigDecimal amount = new BigDecimal("50");
JSONObject jsonObject = myLoadedWallet.send("tz1PoRsJJCQxcfqupCvEkNwoKpPCPJJAWbfW", "tz1hjWhmmaLbtzrqhkAoeFiTp5U9mt7kcjtu", amount, "0", "", "");
System.out.println(jsonObject.get("result"));
`

Loaded the wallet from disk:
tz1PoRsJJCQxcfqupCvEkNwoKpPCPJJAWbfW
100 ꜩ
Could not apply operation because: proto.002-PsYLVpVv.contract.unrevealed_key

**Comment by munakaya** [comment]
https://github.com/keefertaylor/TezosKit/blob/master/Sources/Client/TezosClient.swift#L48 

I think reval operation is needed for transfering funds.

**Comment by LMilfont** [comment]
Hi. Thank you for your comment. I also think reveal operation is needed before transfering funds. I will create a method to do the reveal operation and add it to the next version.

**Comment by munakaya** [comment]
Since I added some test code for reveal, it worked.
